---
settings:
  name: Catalyst Migration
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: SANtricity 11.5 
    url: "/index.html"
  - section: sm-interface
  - section: sm-storage
  - section: sm-mirroring
  - section: sm-hardware
  - section: sm-settings
  - section: sm-support
