---
settings:
  name: "SANtricity 11.5"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
  - title: SANtricity 11.5 docs
    url: "/index.html"
  - section: sm-interface
  - section: sm-storage
  - section: sm-mirroring
  - section: sm-hardware
  - section: sm-settings
  - section: sm-support
  - title: Legal notices
    url: /legal-notices.html
