---
permalink: sm-mirroring/requirements-for-using-asynchronous-mirroring.html
sidebar: sidebar
keywords: requirements, use, asynchronous, mirroring
summary: "If you plan to use the Asynchronous Mirroring feature, keep the following requirements in mind."
---
= Requirements for using asynchronous mirroring
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
If you plan to use the Asynchronous Mirroring feature, keep the following requirements in mind.

== SANtricity Unified Manager

To use asynchronous mirroring, the following conditions must be set up:

* The Web Services Proxy service is running.
* SANtricity Unified Manager is running on your local host through an HTTPS connection.
* Each controller in both the primary array and secondary array must have an Ethernet management port configured and must be connected to your network.
* SANtricity Unified Manager is showing valid SSL certificates for the storage array. You can accept a self-signed certificate or install your own security certificate using Unified Manager and navigating to menu:Certificate[Certificate Management].
* SANtricity System Manager is launched from a Unified Manager.
* You must have discovered the two storage arrays you want to mirror data between. Then, from Unified Manager, you select the primary volume's storage array and click *Launch* to open the browser-based SANtricity System Manager.

== Storage arrays

* You must have two storage arrays.
* Each controller in both the primary array and secondary array must have an Ethernet management port configured and must be connected to your network.
* Each storage array must have two controllers.
* The primary and secondary volumes' storage arrays can run different OS versions. The minimum version supported is 7.84.
* You must know the password for the local and remote storage arrays.
* You must have enough free capacity on the remote storage array to create a secondary volume equal to or greater than the primary volume that you want to mirror.
* Your local and remote storage arrays must be connected through a Fibre Channel fabric or iSCSI interface.

== Supported hardware configurations and connectivity requirements

* Asynchronous mirroring is supported only in dual-controller hardware configurations.
* Communication for the Asynchronous Mirroring feature is supported only on controllers with Fibre Channel (FC) or iSCSI host ports. The feature uses one of the host ports on each controller on both the local storage array and the remote storage array.
* If storage arrays are connected with both FC connections and iSCSI connections, one asynchronous mirror group can be mirrored over FC and another asynchronous mirror group can be mirrored over iSCSI.

== Mirrored volume candidates

* RAID level, caching parameters, and segment size can be different on the primary and secondary volumes of an asynchronous mirrored pair.
* The secondary volume must be at least as large as the primary volume.
* A volume can participate in only one mirror relationship.

== Reserved capacity

* A reserved capacity volume is required for a primary volume and for a secondary volume in a mirrored pair for logging write information to recover from controller resets and other temporary interruptions.
* Because both the primary volume and the secondary volume in a mirrored pair require additional reserved capacity, you must ensure that you have free capacity available on both storage arrays in the mirror relationship.

== Drive Security feature

* If you are using secure-capable drives, the primary volume and the secondary volume must have compatible security settings. This restriction is not enforced; therefore, you must verify it yourself.
* If you are using secure-capable drives, the primary volume and the secondary volume should use the same drive type. This restriction is not enforced; therefore, you must verify it yourself.
* If you are using Data Assurance (DA), the primary volume and the secondary volume must have the same DA settings.
