---
permalink: sm-mirroring/requirements-for-using-synchronous-mirroring.html
sidebar: sidebar
keywords: 
summary: 'If you use the Synchronous Mirroring feature, keep the following requirements in mind.'
---
= Requirements for using synchronous mirroring
:icons: font
:imagesdir: ../media/

[.lead]
If you use the Synchronous Mirroring feature, keep the following requirements in mind.

== SANtricity Unified Manager

Because the Synchronous Mirroring feature requires the management of multiple storage arrays, you must have the browser-based SANtricity Unified Manager installed, and have discovered the two storage arrays you want to mirror data between. Then, from Unified Manager, you select the primary volume's storage array and click *Launch* to open the browser-based SANtricity System Manager.

== Storage arrays

* You must have two storage arrays.
* Each storage array must have two controllers.
* The primary and secondary volumes' storage arrays can run different OS versions. The minimum version supported is 7.84.
* You must know the password for the local and remote storage arrays.
* You must have enough free capacity on the remote storage array to create a secondary volume equal to or greater than the primary volume that you want to mirror.
* Your local and remote storage arrays must be connected through a Fibre Channel fabric.

== Supported hardware configuration and connections

* Synchronous mirroring is supported only in dual-controller hardware configurations.
* Communication for synchronous mirroring is supported only on controllers with Fibre Channel (FC) host ports.
* Synchronous mirroring uses the highest numbered host port on each controller on both the local storage array and the remote storage array. Controller host bus adapter (HBA) host port 4 is typically reserved for mirror data transmission.

== Mirrored volume candidates

* RAID level, caching parameters, and segment size can be different on the primary and secondary volumes of a synchronous mirrored pair.
* The primary and secondary volumes in a synchronous mirrored pair must be standard volumes. They cannot be thin volumes or snapshot volumes.
* The secondary volume must be at least as large as the primary volume.
* Only the primary volume may have snapshots associated with it and/or be the source or target volume in a volume copy operation.
* A volume can participate in only one mirror relationship.

== Reserved capacity

* Reserved capacity is required for a primary volume and for a secondary volume for logging write information to recover from controller resets and other temporary interruptions.
* The reserved capacity volumes are created automatically when synchronous mirroring is activated. Because both the primary volume and the secondary volume in a mirrored pair require reserved capacity, you must ensure that you have enough free capacity available on both storage arrays that are participating in the synchronous mirror relationship.

== Drive Security feature

* If you are using secure-capable drives, the primary volume and the secondary volume must have compatible security settings. This restriction is not enforced; therefore, you must verify it yourself.
* If you are using secure-capable drives, the primary volume and the secondary volume should use the same drive type. This restriction is not enforced; therefore, you must verify it yourself.
 ** If the primary volume uses Full Disk Encryption (FDE) drives, the secondary volume should use FDE drives.
 ** If the primary volume uses Federal Information Processing Standards 140-2 (FIPS) validated drives, the secondary volume should use FIPS 140-2 validated drives.
* If you are using Data Assurance (DA), the primary volume and the secondary volume must have the same DA settings.
