---
permalink: sm-mirroring/synchronous-mirroring-activation.html
sidebar: sidebar
keywords: synchronous, mirror, activation
summary: "The Synchronous Mirroring feature is automatically activated when the first synchronous mirrored pair is created on a storage array."
---
= Synchronous mirroring activation
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
The Synchronous Mirroring feature is automatically activated when the first synchronous mirrored pair is created on a storage array.

When the Synchronous Mirroring feature is activated, System Manager performs the following actions:

* Reserves the highest-numbered port of the controller's HIC for mirror data transmission.
+
I/O requests received on this port are accepted only from the remote preferred controller owner of the secondary volume in the mirrored pair. (Reservations on the primary volume are allowed.)

* Creates two reserved capacity volumes, one for each controller, which are used for logging write information to recover from controller resets and other temporary interruptions.
+
The capacity of each volume is 128 MiB. However, if the volumes are placed in a pool, 4 GiB will be reserved for each volume.

With the Synchronous Mirroring feature, there are limits to the number of volumes that are supported on a given storage array. Before you activate Synchronous Mirroring, make sure that the number of configured volumes on your storage array is less than the supported limit. When Synchronous Mirroring is active, the two reserved capacity volumes that are created count against the volume limit.

If you need to deactivate Synchronous Mirroring at a later time, go to menu:Storage[Synchronous Mirroring > Uncommon Tasks > Deactivate].
