---
permalink: sm-hardware/configure-nvme-over-roce-ports-hardware.html
sidebar: sidebar
keywords: configure, nvme, roce, ports
summary: "If your controller includes a connection for NVMe over RoCE (RDMA over Converged Ethernet), you can configure the NVMe port settings from the Hardware page or the System page."
---
= Configure NVMe over RoCE ports
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
If your controller includes a connection for NVMe over RoCE (RDMA over Converged Ethernet), you can configure the NVMe port settings from the Hardware page or the System page.

== Before you begin

* Your controller must include an NVMe over RoCE host port; otherwise, the NVMe over RoCE settings are not available in System Manager.
* You must know the IP address of the host connection.

== About this task

You can access the NVMe over RoCE configuration from the Hardware page or from menu:Settings[System]. This task describes how to configure the ports from the *Hardware* page.

[NOTE]
====
The NVMe over RoCE settings and functions appear only if your storage array's controller includes an NVMe over RoCE port.
====

== Steps

. Select *Hardware*.
. If the graphic shows the drives, click *Show back of shelf*.
+
The graphic changes to show the controllers instead of the drives.

. Click the controller with the NVMe over RoCE port you want to configure.
+
The controller's context menu appears.

. Select *Configure NVMe over RoCE ports*.
+
The *Configure NVMe over RoCE Ports dialog* box opens.

. In the drop-down list, select the HIC port you want to configure.
. Click *Next*.
+
To see all port settings, click the Show more port settings link on the right of the dialog box.
+
Field Details
+
[options="header"]
|===
| Port Setting| Description
a|
Configured ethernet port speed
a|
Select the speed that matches the speed capability of the SFP on the port.
a|
Enable IPv4 / Enable IPv6
a|
Select one or both options to enable support for IPv4 and IPv6 networks.
[NOTE]
====
If you want to disable port access, deselect both check boxes.
====
a|
MTU size     (Available by clicking *Show more port settings*.)
a|
If necessary, enter a new size in bytes for the Maximum Transmission Unit (MTU).

The default Maximum Transmission Unit (MTU) size is 1500 bytes per frame. You must enter a value between 1500 and 9000.

|===
If you selected Enable IPv4, a dialog box opens for selecting IPv4 settings after you click Next. If you selected Enable IPv6, a dialog box opens for selecting IPv6 settings after you click Next. If you selected both options, the dialog box for IPv4 settings opens first, and then after you click Next, the dialog box for IPv6 settings opens.

. Configure the IPv4 and/or IPv6 settings, either automatically or manually.
+
Field Details
+
[options="header"]
|===
| Port setting| Description
a|
Automatically obtain configuration
a|
Select this option to obtain the configuration automatically.
a|
Manually specify static configuration
a|
Select this option, and then enter a static address in the fields. (If desired, you can cut and paste addresses into the fields.) For IPv4, include the network subnet mask and gateway. For IPv6, include the routable IP address and router IP address.
|===

. Click *Finish*.
