---
permalink: sm-settings/concept_what_is_cache_block_size.html
sidebar: sidebar
keywords: 
summary: 'The storage array’s controller organizes its cache into "blocks," which are chunks of memory that can be 4, 8, 16, or 32 KiBs in size. All volumes on the storage system share the same cache space; therefore, the volumes can have only one cache block size.'
---
= What is cache block size?
:icons: font
:imagesdir: ../media/

[.lead]
The storage array's controller organizes its cache into "blocks," which are chunks of memory that can be 4, 8, 16, or 32 KiBs in size. All volumes on the storage system share the same cache space; therefore, the volumes can have only one cache block size.

[NOTE]
====
Cache blocks are not the same as the 512-byte blocks that are used by the logical block system of the disks.
====

Applications use different block sizes, which can have an impact on storage performance. By default, the block size in System Manager is 8 KiB, but you can set the value to 4, 8, 16, or 32 KiBs. A smaller size is a good choice for file systems or database applications. A larger size is a good choice for applications that require large data transfer, sequential I/O, or high bandwidth, such as multimedia.
