---
permalink: sm-settings/import-trusted-certificates-for-controllers-acting-as-client.html
sidebar: sidebar
keywords: import, trusted, certificates, controllers
summary: "After receiving digital certificates from a certificate authority (CA), you can import the certificate chain (intermediate and root) for the controllers."
---
= Import trusted certificates for controllers
:icons: font
:imagesdir: ../media/

[.lead]
After receiving digital certificates from a certificate authority (CA), you can import the certificate chain (intermediate and root) for the controllers.

.Before you begin

* You must be logged in with a user profile that includes Security admin permissions. Otherwise, certificate functions do not appear.
* You have generated a certificate signing request (.CSR file) and sent it to the CA.
* The CA returned trusted certificate files.
* The certificate files are installed on your local system.

.About this task

This task describes how to upload the trusted certificates for the storage array's controllers.

.Steps

. Select menu:Settings[Certificates].
. From the *Trusted* tab, select *Import*.
+
A dialog box opens for importing the trusted certificate files.

. Click *Browse* to select the certificate files for the controllers.
+
The file names display in the dialog box.

. Click *Import*.

.Results

The files are uploaded and validated.

.After you finish

Import the management certificate.
