---
permalink: sm-settings/view-imported-certificates.html
sidebar: sidebar
keywords: 
summary: 'From the Certificates page, you can view the certificate type, issuing authority, and the valid date range of certificates you previously imported.'
---
= View imported certificate information
:icons: font
:imagesdir: ../media/

[.lead]
From the Certificates page, you can view the certificate type, issuing authority, and the valid date range of certificates you previously imported.

== Before you begin

* You must be logged in with a user profile that includes Security admin permissions. Otherwise, certificate functions do not appear.

== About this task

This task describes how to view information for user-installed or pre-installed certificates.

== Steps

. Select *Settings* > *Certificates*.
. Select one of the tabs to view information about management certificates for the controllers, trusted certificates, and certificates for a key management server.
+
|===
| Tab| Description
a|
Array Management
a|
View information about all the server certificates imported for the controllers.
a|
Trusted
a|
View information about all the trusted (root) certificates imported for the controllers.     Use the filter field under *Show certificates that are...* to view either user-installed or pre-installed certificates.

 ** *User-installed*. Certificates that a user uploaded to the storage array (includes trusted certificates, LDAPS certificates, and Identity Federation certificates).
 ** *Pre-installed*. Certificates included with the storage array.

a|
Key Management
a|
View information about all the management (signed) certificates imported for an external key management server.
|===
